### ISSUE TITLE
pip version not working (NetworkX error - Node not found)

### ISSUE THREAD

**Issue by wariobrega** [anthbapt/multixrank#3]
Hello,

I was trying to use the `pip` version of multiXRank for my multilayered networks but apparently, there is an issue in NetworkX (`Node can't be found` error).

I can provide some details on it and how I am building the multilayer, if needed.
 
The  problem  seem to be fixed when  I  compile the library from source (using the `python setup.py install` command) in a dedicated conda environment.

Can you confirm that the developer version is currently the working one?

Thanks!

Daniele

**Comment by anthbapt** [comment]
Hello, 

Yes this problem comes from a conflict between the last version of networkX and our package multiXrank, this error still exists in the pip version of multiXrank, but we corrected it in the GitHub version. So we advise you to use the GitHub version until we will update the new pip version. We will add several corrections in the 0.1 pip version of multiXWrank. We will deliver it very soon.

Best regards,

Anthony Baptista

**Comment by anthbapt** [comment]
The version of Multixrank 0.1 is available! This new release corrects all the reported bugs.
To be sure to install the new version use:

pip install multixrank==0.1
