### ISSUE TITLE
Adding Node Attributes 

### ISSUE THREAD

**Issue by troks27** [anthbapt/multixrank#8]
Hello, 

Thank you for developing this tool. I am looking at using it to create a multiplex graph of PPI, Reactome, and  TF-gene data, with the nodes being genes. My goal is to take gene expression data from each cell in a scRNAseq dataset, map it to the nodes, and create a feature embedding for each cell that I can use to train a GNN. 

I have two questions. 

1) Is it possible to use node features (such as gene expression data) with your model?
2) Is it possible to label edges, such as in the reactome file, the edges are directed, and I want to incorporate the pathway name of each edge.

Thanks for the help!

**Comment by troks27** [comment]
These are the graph structures I wish to use. Reactome is directed and I would like the edge features to be the pathway names. STRING is not directed and the edge weights are interaction confidence. Gene regulatory network is directed and unweighted. 

https://drive.google.com/drive/folders/1Zdm_ZFEOnoAbsMYFDxMzYsQP_FFNUg2Q?usp=sharing

**Comment by troks27** [comment]
If no direct method for node attributes exist, I was also thinking that I could potentially use a bipartite graph to represent this, such that the graph would be a Monoplex graph with the genes being expressed in the cell, then the edges would connect the expressed genes with the matching genes in each of the layers of the multiplex graph. Then , the edge weights of these connections could be the gene expression values?

Let me know what you think of my first question, and if there isn't a direct way to do what I am looking to do would this indirect method work?

Also, if I do not want to bias my results, how can I pick the correct seed nodes? The whole point of me using this is to derive embeddings which a neural network will use to derive meaning from, thus I do not want to bias the output.

**Comment by anthbapt** [comment]
Hello,

Thank you for using MultiXrank!

Regarding your first question, utilizing node features for the initial restart probability is feasible. However, it's essential to note that the random walk (RW) process relies on the transition matrix, which incorporates information solely from the edges. Therefore, while node information can influence the restart process, it doesn't directly impact the walking process. In conclusion, instead of employing a fixed set of seeds, consider using a distribution aligned with your gene expression distribution. This approach aligns naturally with the problem, although your proposed solution could also be effective.

For your second question about labeling edges, it's not possible to integrate the label directly into the RW process. Nevertheless, a post-processing visualisation can be created to combine the outcomes of MultiXrank with the edge labels, providing a comprehensive solution to address this aspect.
